* InfoApi V 4.0.0(JA)

* Documentation


Info APi works alright, but there are some tweaks that could be done to improve it.  This is my attempt.

each request needs its secret key at the end like: 
http://server:25577/version?secret


** Existing API Queries:
   - http://localhost:25577/playerlist?secret=secret
   - http://localhost:25577/playerlist/world?secret=secret
   - http://localhost:25577/maxplayer?secret=secret
   - http://localhost:25577/onlinemode?secret=secret
   - http://localhost:25577/version?secret=secret
   - http://localhost:25577/ram (returns as: FREE MAX TOTAL)
   - http://localhost:25577/cpu (CPU core number)

** Possible Api Querys:
   - http://server:25577/onlineplayer 
   - http://server:25577/onlineplayer/WORLDNAME 
   - http://server:25577/playerlist 
   - http://server:25577/playerlist/WORLDNAME 
   - http://server:25577/maxplayer 
   - http://server:25577/temp/WORLDNAME (Temperature at Spawn ) 
   - http://server:25577/time/WORLDNAME 
   - http://server:25577/say/text_to_say 
   - http://server:25577/cmd/cmd_attribute_another

** Config File
#+begin_src yaml :tangle ./src/main/resources/config.yml
# Horribly insecure password here.  FOR THE LOVE OF GOD, CHANGE THIS
# Uncomment the next like and change "secret" to something that doesn't suck.
# secretKey: secret
secretKey: secret
port: 25577
npcSaveMode: true

# Logging requests might not be the smartest thing in the world, because the secret is spit out in the log.
# This will change in the future.  I hope.   In the meantime, if you're really worried, you probably
# Want to uncomment the next line:
#logRequests; false
logRequests: true
#+end_src
** Installation 
   Put the main InfoApi.jar in your plugins directory.  Put the 'endpoints' directory inside of plugins/InfoApi/

*** From the original doc:
Please note: this Plugin will give an Error if you do /reload, because the API Server CAN'T get reloaded at the moment. Thats not really
an problem, but you should know. Also there can be an Error on Shutdown... im sorry about that

** Communicating with the API
   My version of the InfoApi plugin is shaping up to be a restful API.  This means the following:
   - Any time the server runs into an internal error condition (exception thrown, etc.) it will return a HTTP 500 status code.
   - Any time the server can't find the entity/endpoint you are looking for, then it will throw a 404 instead
   - Any time the server found what you are looking for, but the response is empty, you will get an empty response with a 200 error code.
   - Each endpoint will provide a response to an HTTP OPTIONS request.  Right now it just provides its currently mounted location, and a
     small description of what it does. But this will be expanded later. 

** Example Usage PHP:
#+begin_src php
$apiurl = "http://server:25577/onlineplayer"
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $apiurl);
curl_setopt($ch, CURLOPT_HEADER, 1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_TIMEOUT, 1000);
$onlineplayer = curl_exec($ch);
echo $onlineplayer;
#+end_src

