name: InfoApi
main: seta.infoapi.InfoApi
version: 0.4.0
description: Provides Information about Minecraft Server queryable by a RESTful HTTP Request
author: seta
authors: [seta, janka, jonnay]
website: https://github.com/jonnay/InfoApi